DROP TABLE IF EXISTS attempt_details CASCADE;
DROP TABLE IF EXISTS attempt_sessions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
