basePath: /
definitions:
  model.AnswerOptionDto:
    properties:
      content:
        type: string
      id:
        type: string
      isCorrect:
        type: boolean
    required:
    - content
    type: object
  model.CreateAnswerOptionDto:
    properties:
      content:
        type: string
      isCorrect:
        type: boolean
    required:
    - content
    - isCorrect
    type: object
  model.CreateQuestionBatchItem:
    properties:
      content:
        type: string
      options:
        items:
          $ref: '#/definitions/model.CreateAnswerOptionDto'
        minItems: 1
        type: array
      timeLimit:
        minimum: 1
        type: integer
    required:
    - content
    - options
    - timeLimit
    type: object
  model.CreateQuestionBatchRequest:
    properties:
      level:
        enum:
        - easy
        - medium
        - hard
        type: string
      questions:
        items:
          $ref: '#/definitions/model.CreateQuestionBatchItem'
        minItems: 1
        type: array
      topicId:
        type: string
    required:
    - level
    - questions
    - topicId
    type: object
  model.CreateTopicRequest:
    properties:
      level_settings:
        items:
          $ref: '#/definitions/model.LevelSettingDto'
        type: array
      max_attempts:
        minimum: 1
        type: integer
      name:
        type: string
    required:
    - level_settings
    - max_attempts
    - name
    type: object
  model.GeneralResponse:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      message:
        type: string
    type: object
  model.LevelSettingDto:
    properties:
      false_score:
        type: integer
      level:
        enum:
        - easy
        - medium
        - hard
        type: string
      true_score:
        type: integer
    required:
    - level
    type: object
  model.LoginRequest:
    properties:
      identifier:
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  model.LoginResponse:
    properties:
      access_token:
        type: string
      permissions:
        additionalProperties: true
        type: object
      refresh_token:
        type: string
      roles:
        items:
          type: string
        type: array
      user:
        $ref: '#/definitions/model.UserDto'
      username:
        type: string
    type: object
  model.QuestionResponse:
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      level:
        type: string
      options:
        items:
          $ref: '#/definitions/model.AnswerOptionDto'
        type: array
      timeLimit:
        type: integer
      topicId:
        type: string
      updatedAt:
        type: string
    type: object
  model.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      rotated:
        type: boolean
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        maxLength: 50
        minLength: 3
        type: string
      gender:
        enum:
        - male
        - female
        type: string
      last_name:
        maxLength: 50
        type: string
      password:
        maxLength: 50
        minLength: 6
        type: string
      profile_picture_url:
        type: string
      username:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - first_name
    - password
    - username
    type: object
  model.RegisterResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      profile_picture_url:
        type: string
      username:
        type: string
    type: object
  model.TopicResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      level_settings:
        items:
          $ref: '#/definitions/model.LevelSettingDto'
        type: array
      max_attempts:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.UpdateQuestionRequest:
    properties:
      content:
        type: string
      options:
        items:
          $ref: '#/definitions/model.AnswerOptionDto'
        minItems: 1
        type: array
      timeLimit:
        minimum: 1
        type: integer
    required:
    - content
    - options
    - timeLimit
    type: object
  model.UpdateTopicRequest:
    properties:
      level_settings:
        items:
          $ref: '#/definitions/model.LevelSettingDto'
        type: array
      max_attempts:
        minimum: 1
        type: integer
      name:
        type: string
    required:
    - level_settings
    - max_attempts
    - name
    type: object
  model.UserDto:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      profile_picture_url:
        type: string
      status:
        type: string
    type: object
  model.UserProfileResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      permissions:
        additionalProperties: true
        type: object
      profile_picture_url:
        type: string
      roles:
        items:
          type: string
        type: array
      status:
        type: string
      username:
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Baseline project using Go Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Fiber Clean Architecture
  version: 1.0.0
paths:
  /api/v1/authentication/login:
    post:
      consumes:
      - application/json
      description: login a user.
      parameters:
      - description: Login Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
      summary: login user
      tags:
      - Authentication
  /api/v1/authentication/logout:
    post:
      consumes:
      - application/json
      description: log out user and clear tokens/cookies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  type: string
              type: object
      security:
      - JWT: []
      summary: logout user
      tags:
      - Authentication
  /api/v1/authentication/refresh:
    post:
      consumes:
      - application/json
      description: refresh access token using refresh token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.RefreshTokenResponse'
              type: object
      security:
      - JWT: []
      summary: refresh token
      tags:
      - Authentication
  /api/v1/authentication/register:
    post:
      consumes:
      - application/json
      description: register a new user.
      parameters:
      - description: Register Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.RegisterResponse'
              type: object
      summary: register user
      tags:
      - Authentication
  /api/v1/questions:
    get:
      consumes:
      - application/json
      description: list all questions.
      parameters:
      - description: Filter by topic ID
        in: query
        name: topicId
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit number
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.QuestionResponse'
                  type: array
              type: object
      summary: list questions
      tags:
      - Question
  /api/v1/questions/{id}:
    delete:
      consumes:
      - application/json
      description: delete a question by UUID.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  type: string
              type: object
      security:
      - JWT: []
      summary: delete question
      tags:
      - Question
    get:
      consumes:
      - application/json
      description: get a specific question by UUID.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.QuestionResponse'
              type: object
      summary: get question
      tags:
      - Question
    put:
      consumes:
      - application/json
      description: update an existing question and sync its answers.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Question Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateQuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.QuestionResponse'
              type: object
      security:
      - JWT: []
      summary: update question
      tags:
      - Question
  /api/v1/questions/batch:
    post:
      consumes:
      - application/json
      description: create questions in batch for a topic.
      parameters:
      - description: Create Questions Batch Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateQuestionBatchRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.QuestionResponse'
                  type: array
              type: object
      security:
      - JWT: []
      summary: create questions batch
      tags:
      - Question
  /api/v1/topics:
    get:
      consumes:
      - application/json
      description: list all topics.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit number
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.TopicResponse'
                  type: array
              type: object
      summary: list topics
      tags:
      - Topic
    post:
      consumes:
      - application/json
      description: create a new topic.
      parameters:
      - description: Create Topic Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateTopicRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.TopicResponse'
              type: object
      security:
      - JWT: []
      summary: create topic
      tags:
      - Topic
  /api/v1/topics/{id}:
    delete:
      consumes:
      - application/json
      description: delete a topic by UUID.
      parameters:
      - description: Topic ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  type: string
              type: object
      security:
      - JWT: []
      summary: delete topic
      tags:
      - Topic
    get:
      consumes:
      - application/json
      description: get a specific topic by UUID.
      parameters:
      - description: Topic ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.TopicResponse'
              type: object
      summary: get topic
      tags:
      - Topic
    put:
      consumes:
      - application/json
      description: update an existing topic.
      parameters:
      - description: Topic ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Topic Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateTopicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.TopicResponse'
              type: object
      security:
      - JWT: []
      summary: update topic
      tags:
      - Topic
  /api/v1/users/me:
    get:
      consumes:
      - application/json
      description: gets current user profile based on JWT claim.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserProfileResponse'
              type: object
      security:
      - JWT: []
      summary: get profile
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: Authorization For JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
