basePath: /
definitions:
  model.GeneralResponse:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      message:
        type: string
    type: object
  model.LoginRequest:
    properties:
      identifier:
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  model.LoginResponse:
    properties:
      access_token:
        type: string
      permissions:
        additionalProperties: true
        type: object
      refresh_token:
        type: string
      roles:
        items:
          type: string
        type: array
      user:
        $ref: '#/definitions/model.UserDto'
      username:
        type: string
    type: object
  model.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      rotated:
        type: boolean
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        maxLength: 50
        minLength: 3
        type: string
      gender:
        enum:
        - male
        - female
        type: string
      last_name:
        maxLength: 50
        type: string
      password:
        maxLength: 50
        minLength: 6
        type: string
      profile_picture_url:
        type: string
      username:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - first_name
    - password
    - username
    type: object
  model.RegisterResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      profile_picture_url:
        type: string
      username:
        type: string
    type: object
  model.UserDto:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      profile_picture_url:
        type: string
      status:
        type: string
    type: object
  model.UserProfileResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      permissions:
        additionalProperties: true
        type: object
      profile_picture_url:
        type: string
      roles:
        items:
          type: string
        type: array
      status:
        type: string
      username:
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Baseline project using Go Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Fiber Clean Architecture
  version: 1.0.0
paths:
  /api/v1/authentication/login:
    post:
      consumes:
      - application/json
      description: login a user.
      parameters:
      - description: Login Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LoginResponse'
              type: object
      summary: login user
      tags:
      - Authentication
  /api/v1/authentication/logout:
    post:
      consumes:
      - application/json
      description: log out user and clear tokens/cookies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  type: string
              type: object
      security:
      - JWT: []
      summary: logout user
      tags:
      - Authentication
  /api/v1/authentication/refresh:
    post:
      consumes:
      - application/json
      description: refresh access token using refresh token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.RefreshTokenResponse'
              type: object
      security:
      - JWT: []
      summary: refresh token
      tags:
      - Authentication
  /api/v1/authentication/register:
    post:
      consumes:
      - application/json
      description: register a new user.
      parameters:
      - description: Register Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.RegisterResponse'
              type: object
      summary: register user
      tags:
      - Authentication
  /api/v1/users/me:
    get:
      consumes:
      - application/json
      description: gets current user profile based on JWT claim.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserProfileResponse'
              type: object
      security:
      - JWT: []
      summary: get profile
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: Authorization For JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
